glud_service_examen:
    resource: "@GludServiceBundle/Controller/ExamenController.php"
    type:     annotation

glud_service:
    resource: "@GludServiceBundle/Resources/config/routing.php"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
